[features]
seeds = false
skip-lint = false

[programs.localnet]
diap_agent_network = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
diap_token = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
diap_payment_core = "HmbTLCmaGvZhKnn1Zfa1JVk7jmkAuCWx3nNSeXDVoEk1"
diap_payment_channel = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
diap_payment_privacy = "3WEwXwX9TjF7w4p4q4q4q4q4q4q4q4q4q4q4q4q4q4q"
diap_verification = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU"
diap_governance = "5mK7w9e9q4q4q4q4q4q4q4q4q4q4q4q4q4q4q4q4q"
diap_subscription = "8yH6fF8e9r4q4q4q4q4q4q4q4q4q4q4q4q4q4q4q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
